services:
  main:
    build: .
    container_name: multiplexer_server
    ports:
      - "8080:80"
      - "1935:1935"    
    volumes:
      - ./html:/opt/nginx/html
      - ./nginx.conf:/opt/nginx/conf/nginx.conf:ro
    restart: unless-stopped
